maven_build:
  stage: test
  image: maven:3.3.9-jdk-8
  script:
    - echo "Building project with maven"
    - mvn verify

deploy-to-staging:
  stage: deploy
  image: maven:3.3.9-jdk-8
  services:
    - docker:dind
  artifacts:
    paths:
      - target/*.war

  script:
    - echo "Deploy to staging server"
    - mvn package
    - docker cp target/inventorymanager-webapp.war tomcat-mysql-run:/opt/tomcat/webapps/inventorymanager-webapp.war
  environment:
    name: staging
    url: http://ec2-52-87-247-183.compute-1.amazonaws.com/root/SoftEngStudioFall17:8888/inventorymanager-webapp/
  #only: # Enable when testing is done
  #- master