stages:
  - build
  - test
  - staging
  - production

maven_build:
 stage: build
 image: maven:3.3.9-jdk-8
 script:
  - echo "Building project with maven"
  - mvn compile
 except:
  - schedules

maven_tests:
 stage: test
 image: maven:3.3.9-jdk-8
 script:
  - echo "Testing project with maven"
  - mvn '-Dtest=edu.brandeis.**.*Test' test

deploy-to-staging:
 stage: staging
 image: maven:3.3.9-jdk-8
 artifacts:
  paths:
   - target/*.war
 script:
  - echo "Deploy to staging server"
  - TOMCAT_HOST=$(ip route show | awk '/default/ {print $3}')
  - mvn test # We are testing before hand because we are changing a file that the test check against.
  - sed -i -e 's/'value=\"root\"'/'value=\"$MYSQL_USER_STAGING\"'/g' ./src/main/resources/META-INF/spring/datasource-tx-jpa.xml
  - sed -i -e 's/'value=\"mysql\"'/'value=\"$MYSQL_PASS_STAGING\"'/g' ./src/main/resources/META-INF/spring/datasource-tx-jpa.xml
  - mvn package -Dmaven.test.skip=true # Disabling test since we already ran tests before but within this same process.
  - curl -T "target/inventorymanager-webapp.war" "http://tomcat:${TOMCAT_PASSWORD}@${TOMCAT_HOST}:8888/manager/text/deploy?path=/inventorymanager-webapp&update=true"
 environment:
  name: staging
  url: http://$STAGING_HOST:8888/inventorymanager-webapp/
 only:
  - master
 except:
  - schedules

deploy-to-production:
 stage: production
 image: maven:3.3.9-jdk-8
 artifacts:
  paths:
   - target/*.war
 script:
  - echo "Deploy to production server"
  - mvn test # We are testing before hand because we are changing a file that the test check against.
  - sed -i -e 's/'value=\"root\"'/'value=\"$MYSQL_USER_PRODUCTION\"'/g' ./src/main/resources/META-INF/spring/datasource-tx-jpa.xml
  - sed -i -e 's/'value=\"mysql\"'/'value=\"$MYSQL_PASS_PRODUCTION\"'/g' ./src/main/resources/META-INF/spring/datasource-tx-jpa.xml
  - mvn package -Dmaven.test.skip=true # Disabling test since we already ran tests before but within this same process.
  - curl -T "target/inventorymanager-webapp.war" "http://tomcat:${TOMCAT_PASS_DEPLOYMENT}@${PRODUCTION_HOST}/manager/text/deploy?path=/&update=true"
 environment:
  name: production
  url: http://$PRODUCTION_HOST/
 only:
  - master
 when: manual

sql-schema-to-staging:
 stage: staging
 image: mysql:5.7
 script:
  - mysql -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST < ./src/main/resources/META-INF/sql/schema.sql
  - mysqlcheck -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST $DB_NAME
 environment:
  name: sql/schema-staging
 only:
  - master
 when: manual

sql-schema-to-production:
 stage: production
 image: mysql:5.7
 script:
  - mysql -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST < ./src/main/resources/META-INF/sql/schema.sql
  - mysqlcheck -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST $DB_NAME
 environment:
  name: sql/schema-production
 only:
  - master
 when: manual

sql-insert-to-staging:
 stage: staging
 image: mysql:5.7
 script:
  - mysql -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST < ./src/main/resources/META-INF/sql/test-data.sql
  - mysqlcheck -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST $DB_NAME
 environment:
  name: sql/insert-sample-data-staging
 only:
  - master
 when: manual

sql-insert-to-production:
 stage: production
 image: mysql:5.7
 script:
  - mysql -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST < ./src/main/resources/META-INF/sql/test-data.sql
  - mysqlcheck -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST $DB_NAME
 environment:
  name: sql/insert-sample-data-production
 only:
  - master
 when: manual

sql-backup-of-staging:
 stage: staging
 image: mysql:5.7
 script:
  - mysqlcheck -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST $DB_NAME
  - mysqldump --single-transaction -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST $DB_NAME > dump_file.sql
 environment:
  name: sql/backup-of-staging
 artifacts:
  paths:
   - ./*.sql
 only:
  - master
 when: manual

sql-backup-of-production:
 stage: production
 image: mysql:5.7
 script:
  - mysqlcheck -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST $DB_NAME
  - mysqldump --single-transaction -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST $DB_NAME > dump_file.sql
 environment:
  name: sql/backup-of-production
 artifacts:
  paths:
   - ./*.sql
 only:
  - master
 when: manual 

#Please provide a $SQL_BACKUP_JOB_ID when calling this from the REST API.
sql-restore-backup-staging:
 stage: staging
 image: mysql:5.7
 script:
  - apt-get update && apt-get -y install curl
  - FIlENAME=dump_file.sql  
  - HEADER
  - curl -o $SQL_BACKUP_JOB_ID-$FIlENAME "http://ec2-52-90-192-232.compute-1.amazonaws.com/api/v4/projects/1/jobs/$SQL_BACKUP_JOB_ID/artifacts/$FIlENAME?private_token=$TOKEN_API_GITLABCI"
  - mysql -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST < ./$SQL_BACKUP_JOB_ID-$FIlENAME
  - mysqlcheck -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST $DB_NAME
 environment:
  name: sql/restore-staging
 only:
  - master
 when: manual  

test-connection-staging-tomcat-and-mysql-:
 stage: staging
 image: mysql:5.7
 script:
  - apt-get update && apt-get -y install curl
  - TOMCAT_HOST=$(ip route show | awk '/default/ {print $3}')
  - curl --fail "http://tomcat:${TOMCAT_PASSWORD}@${TOMCAT_HOST}:8888/manager/status/all"
  - mysql -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST
  - mysqlcheck -u $MYSQL_USER_STAGING -p$MYSQL_PASS_STAGING -h $STAGING_HOST $DB_NAME
 environment:
  name: integration-test/connection-staging
 only:
  - schedules

test-connection-production-tomcat-and-mysql-:
 stage: production
 image: mysql:5.7
 script:
  - apt-get update && apt-get -y install curl
  - curl --fail "http://tomcat:${TOMCAT_PASS_DEPLOYMENT}@${PRODUCTION_HOST}/manager/status/all"
  - mysql -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST
  - mysqlcheck -u $MYSQL_USER_PRODUCTION -p$MYSQL_PASS_PRODUCTION -h $PRODUCTION_HOST $DB_NAME
 environment:
  name: integration-test/connection-production
 only:
  - schedules