maven_build:
 stage: test
 image: maven:3.3.9-jdk-8
 script:
  - echo "Building project with maven"
  - mvn verify

deploy-to-staging:
 stage: deploy
 image: maven:3.3.9-jdk-8
 artifacts:
  paths:
   - target/*.war
 script:
  - echo "Deploy to staging server"
  - TOMCAT_HOST=$(ip route show | awk '/default/ {print $3}')
  - mysql -u root -p$MYSQL_PASS_STAGING -h localhost < ./src/main/resources/META-INF/sql/schema.sql
  - sed -i -e 's/'value=\"mysql\"'/'value=\"$MYSQL_PASS_STAGING\"'/g' ./src/main/resources/META-INF/spring/datasource-tx-jpa.xml
  - mvn package
  - curl -T "target/inventorymanager-webapp.war" "http://tomcat:${TOMCAT_PASSWORD}@${TOMCAT_HOST}:8888/manager/text/deploy?path=/inventorymanager-webapp&update=true"
 environment:
  name: staging
  url: http://ec2-52-90-192-232.compute-1.amazonaws.com:8888/inventorymanager-webapp/
 only:
  - master

deploy-to-production:
 stage: deploy
 image: maven:3.3.9-jdk-8
 artifacts:
  paths:
   - target/*.war
 script:
  - echo "Deploy to production server"
  - TOMCAT_HOST=ec2-52-23-230-241.compute-1.amazonaws.com
  - mysql -u root -p$MYSQL_PASS_PRODUCTION -h $TOMCAT_HOST < ./src/main/resources/META-INF/sql/schema.sql
  - sed -i -e 's/'value=\"mysql\"'/'value=\"$MYSQL_PASS_PRODUCTION\"'/g' ./src/main/resources/META-INF/spring/datasource-tx-jpa.xml
  - mvn package
  - curl -T "target/inventorymanager-webapp.war" "http://tomcat:${TOMCAT_PASS_DEPLOYMENT}@${TOMCAT_HOST}/manager/text/deploy?path=/&update=true"
 environment:
  name: production
 only:
  - master
 when: manual
