CREATE TABLE SUPPLIER (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , STREETNUM INT NOT NULL
     , STREETNAME VARCHAR(200) NOT NULL
     , CITY VARCHAR(100) NOT NULL
     , STATE VARCHAR(2) NOT NULL
     , ZIPCODE VARCHAR(5) NOT NULL
     , PHONE VARCHAR(20) NOT NULL
     , EDI VARCHAR(10) NOT NULL
     , PAYMENT VARCHAR(100) NOT NULL
     , INCOTERMS VARCHAR(250)
     , PRIMARY KEY (ID)
);
